// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGuJPyRXf5ToSEU8DYW3mRPNhHOi5rngQ',
    appId: '1:676264237837:web:112f5d19011f8f3eed6e44',
    messagingSenderId: '676264237837',
    projectId: 'tiro-mo-mangaung-4ed34',
    authDomain: 'tiro-mo-mangaung-4ed34.firebaseapp.com',
    storageBucket: 'tiro-mo-mangaung-4ed34.firebasestorage.app',
    measurementId: 'G-THSGW05XPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86q4KKpPbcUbU1gm4Olw4b25Xv17qzBU',
    appId: '1:676264237837:android:2738e88d60a969faed6e44',
    messagingSenderId: '676264237837',
    projectId: 'tiro-mo-mangaung-4ed34',
    storageBucket: 'tiro-mo-mangaung-4ed34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0o5bNyoCwtr9ScHDPX0R6Gi-420g7KTc',
    appId: '1:676264237837:ios:813bdaee19965b06ed6e44',
    messagingSenderId: '676264237837',
    projectId: 'tiro-mo-mangaung-4ed34',
    storageBucket: 'tiro-mo-mangaung-4ed34.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0o5bNyoCwtr9ScHDPX0R6Gi-420g7KTc',
    appId: '1:676264237837:ios:813bdaee19965b06ed6e44',
    messagingSenderId: '676264237837',
    projectId: 'tiro-mo-mangaung-4ed34',
    storageBucket: 'tiro-mo-mangaung-4ed34.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGuJPyRXf5ToSEU8DYW3mRPNhHOi5rngQ',
    appId: '1:676264237837:web:7166b0c63193aca0ed6e44',
    messagingSenderId: '676264237837',
    projectId: 'tiro-mo-mangaung-4ed34',
    authDomain: 'tiro-mo-mangaung-4ed34.firebaseapp.com',
    storageBucket: 'tiro-mo-mangaung-4ed34.firebasestorage.app',
    measurementId: 'G-D9M9FHWYWC',
  );
}
